// const baseUrl = 'https://docs.gift'
// const baseUrl = 'https://d-o-d.io'
const baseUrl = 'http://3.36.156.224:8010'
// const baseUrl = 'https://dod-link.com'
export const kakaoLink = 'http://pf.kakao.com/_nfxcTs/chat'
export const privacyPolicy = 'https://www.notion.so/dod-8dcf79f6f2e243f1a7b506b538a5ed92'
export const useOfTerm = 'https://www.notion.so/dod-ad65925f9dc94279aa2b16cedd54bf3c'
export const dodMoreLink = 'https://d-o-d.io/?utm_source=dod&utm_medium=service&utm_campaign=respondent'
export const dodTestLink = 'https://docs.google.com/forms/d/e/1FAIpQLScXygk-Nc_OaLNFZzbAHgL4HtZDKlJsuBr2IxbDkFewLrcR2Q/viewform?usp=sf_link'
export default baseUrl;